version: '3.9'

services:
  firewall:
    image: nginx:alpine
    container_name: firewall
    ports:
      - "80:80"
      - "8000:8000"  # Puerto para el backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_net

  backend:
    build:
      context: ./prueba/prueba/apidiplomadoFinal
      dockerfile: Dockerfile
    image: backend-fastapi
    container_name: backend
    networks:
      - app_net

  frontend:
    build:
      context: ./Taller2/frontProyectoFinal
      dockerfile: Dockerfile
    image: frontend-angular
    container_name: frontend
    networks:
      - app_net

  persistencia:
    image: mongo:latest
    container_name: persistencia
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - app_net

networks:
  app_net:
    driver: bridge