version: '3.9'

services:
  firewall:
    image: nginx:alpine
    container_name: firewall
    ports:
      - "80:80"  # Único puerto expuesto
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_net

  backend:
    build:
      context: ./apidiplomadoFinal
      dockerfile: Dockerfile
    image: backend-fastapi
    container_name: backend
    networks:
      - app_net
    environment:
      - MONGO_URL=mongodb://persistencia:27017/pruebaDB
    depends_on:
      - persistencia

  frontend:
    build:
      context: ./frontProyectoFinal
      dockerfile: Dockerfile
    image: frontend-angular
    container_name: frontend
    networks:
      - app_net

  persistencia:
    image: mongo:latest
    container_name: persistencia
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app_net
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: pruebaDB

volumes:
  mongodb_data:

networks:
  app_net:
    driver: bridge