version: '3.9'

services:
  firewall:
    image: nginx:alpine
    container_name: firewall
    ports:
      - "80:80"
      - "8000:8000"  # Puerto para el backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_net

  backend:
    build:
      context: ./apidiplomadoFinal  # Asegúrate de que este sea el camino correcto
      dockerfile: Dockerfile
    image: backend-fastapi
    container_name: backend
    networks:
      - app_net
    environment:
      - MONGO_URL=mongodb://persistencia:27017/dbproyecto # Añadido para conectar con MongoDB
    depends_on:
      - persistencia

  frontend:
    build:
      context: ./frontProyectoFinal  # Asegúrate de que este sea el camino correcto
      dockerfile: Dockerfile
    image: frontend-angular
    container_name: frontend
    networks:
      - app_net

  persistencia:
    image: mongo:latest
    container_name: persistencia
    volumes:
      - ./data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - app_net
    expose:
      - "27017"  # Puerto interno de MongoDB

networks:
  app_net:
    driver: bridge
